//! Contract bindings, generated by `sol!` from the forge-built artifacts in `abi/` (ABI plus
//! creation and runtime bytecode). Those files are produced by `eth/tools/export-abi.sh` from wyec
//! at the commit pinned in `eth/tools/fetch-wyec.sh`; `export-abi.sh --check` proves they are
//! current. Nothing here is hand-written ABI.
//!
//! - [`WyecBridge`]: the bridge of record: the threshold `mint`, the optimistic `proposeMint` /
//!   `challengeMint` / `executeMint` (wyec-contract-design.md §4.5), the mint rate limit, `burn`,
//!   admin acts.
//! - [`WrappedYcash`]: the wYEC token (ERC-20 + ERC-7802, 8 decimals, capped).

#![allow(clippy::too_many_arguments)]

use alloy::sol;

sol!(
    #[sol(rpc)]
    #[derive(Debug, PartialEq, Eq)]
    WyecBridge,
    "abi/WyecBridge.json"
);

sol!(
    #[sol(rpc)]
    #[derive(Debug, PartialEq, Eq)]
    WrappedYcash,
    "abi/WrappedYcash.json"
);

/// Decodes a revert into the custom error's name and fields, trying the bridge's own errors, the
/// token's (they bubble up through `crosschainMint`/`crosschainBurn`) and a plain `Error(string)`.
/// `None` when the error carries no revert data at all.
pub fn decode_revert(e: &alloy::contract::Error) -> Option<String> {
    if let Some(err) = e.as_decoded_interface_error::<WyecBridge::WyecBridgeErrors>() {
        return Some(format!("{err:?}"));
    }
    if let Some(err) = e.as_decoded_interface_error::<WrappedYcash::WrappedYcashErrors>() {
        return Some(format!("{err:?}"));
    }
    if let Some(err) = e.as_decoded_error::<alloy::sol_types::Revert>() {
        return Some(err.reason);
    }
    e.as_revert_data()
        .map(|data| format!("undecoded revert data {data}"))
}
