// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {Vm} from "forge-std/Vm.sol";
import {stdStorage, StdStorage} from "forge-std/StdStorage.sol";
import {WrappedYcash} from "wyec/WrappedYcash.sol";
import {IWrappedYcash, WyecBridge} from "wyec/WyecBridge.sol";
import {WyecEip712} from "./utils/WyecEip712.sol";

/// Generates (WRITE_VECTORS=true) or checks (default) vectors/eip712.json: EIP-712 domain
/// separators, struct hashes, digests and signatures for fixed keys and inputs, consumed by
/// hawkeye-core and hawkeye-eth (plan §4.4, §7). Every signing case is also *accepted by the pinned
/// WyecBridge*: the test deploys the bridge at the case's verifyingContract on the case's chain id
/// with the case's signer as a 1-of-1 guardian and submits the signature (a Challenge case against
/// a proposal given the case's proposalId). Format: vectors/README.md.
///
///   WRITE_VECTORS=true forge test --mc Eip712VectorsTest     # regenerate
contract Eip712VectorsTest is Test {
    using stdStorage for StdStorage;

    string constant PATH = "vectors/eip712.json";
    string constant WYEC_COMMIT = "cad126a415bdb5e0ae9cf7d05f6bd1b512267efb";
    address constant BRIDGE = 0x5FbDB2315678afecb367f032d93F642f64180aa3; // anvil's first CREATE
    address constant NEW_BRIDGE = 0x00000000000000000000000000000000DeaDBeef;

    uint256[3] internal pks;
    uint256[2] internal chainIds = [uint256(31337), uint256(11155111)];
    string[] internal cases;

    function setUp() public {
        for (uint256 i = 0; i < 3; i++) {
            pks[i] = uint256(keccak256(abi.encodePacked("hawkeye/eip712-vector-key/", vm.toString(i))));
        }
    }

    function test_Eip712Vectors() public {
        for (uint256 c = 0; c < chainIds.length; c++) {
            uint256 cid = chainIds[c];
            domainCase(cid);
            for (uint256 m = 0; m < 3; m++) {
                (bytes32 lockId, uint256 amount, address to) = mintInput(m);
                for (uint256 k = 0; k < 3; k++) {
                    mintCase(cid, k, lockId, amount, to);
                }
            }
            address[] memory g = new address[](3);
            g[0] = vm.addr(pks[2]);
            g[1] = vm.addr(pks[0]);
            g[2] = vm.addr(pks[1]);
            setGuardiansCase(cid, 0, g, 2, 0);
            setGuardiansCase(cid, 0, g, 3, 5);
            setPausedCase(cid, 1, true, 0);
            setPausedCase(cid, 1, false, 1);
            setBridgeCase(cid, 2, NEW_BRIDGE, 3);
            setMintLimitCase(cid, 0, 1000e8, 86400, 2);
            setMintLimitCase(cid, 1, 0, 0, 7);
            for (uint256 m = 0; m < 3; m++) {
                (bytes32 lockId,,) = mintInput(m);
                challengeCase(cid, m, lockId, challengeId(m));
            }
        }

        string memory body = "";
        for (uint256 i = 0; i < cases.length; i++) {
            body = string.concat(body, i == 0 ? "\n    " : ",\n    ", cases[i]);
        }
        string memory json = string.concat(
            "{\n",
            '  "description": "wYEC EIP-712 vectors: generated by eth/test/Vectors.t.sol, every signing case accepted by WyecBridge",\n',
            '  "wyecCommit": "',
            WYEC_COMMIT,
            '",\n',
            '  "cases": [',
            body,
            "\n  ]\n}\n"
        );

        if (vm.envOr("WRITE_VECTORS", false)) {
            vm.writeFile(PATH, json);
        } else {
            assertEq(
                vm.readFile(PATH),
                json,
                "vectors/eip712.json is stale: WRITE_VECTORS=true forge test --mc Eip712VectorsTest"
            );
        }
    }

    // ------------------------------------------------------------------ inputs

    function mintInput(uint256 m) internal pure returns (bytes32 lockId, uint256 amount, address to) {
        if (m == 0) {
            // lockId = sha256(txid_internal || vout u32 LE) (plan §4.1), txid 0x11..11, vout 0
            lockId = sha256(
                abi.encodePacked(
                    bytes32(0x1111111111111111111111111111111111111111111111111111111111111111), bytes4(0)
                )
            );
            return (lockId, 1e8, 0x1111111111111111111111111111111111111111);
        }
        if (m == 1) {
            // vout 1 (LE 01000000), the 21M cap in zatoshi
            lockId = sha256(
                abi.encodePacked(
                    bytes32(0xabababababababababababababababababababababababababababababababab),
                    bytes4(0x01000000)
                )
            );
            return (lockId, 21_000_000 * 1e8, 0xabCDeF0123456789AbcdEf0123456789aBCDEF01);
        }
        return (bytes32(type(uint256).max), 1, 0x0000000000000000000000000000000000000001);
    }

    /// Proposal ids: the first ever, an ordinary one, and the largest a uint96 counter reaches.
    function challengeId(uint256 m) internal pure returns (uint256) {
        if (m == 0) return 1;
        if (m == 1) return 42;
        return type(uint96).max;
    }

    // ------------------------------------------------------------------ cases

    function domainCase(uint256 cid) internal {
        uint256 snap = vm.snapshotState();
        bytes32 ds = WyecEip712.domainSeparator(cid, BRIDGE);
        // The contract's own view of its domain must agree.
        WyecBridge b = deployAt(cid, vm.addr(pks[0]));
        (, string memory name, string memory version, uint256 chainId, address vc,,) = b.eip712Domain();
        assertEq(keccak256(bytes(name)), keccak256("WyecBridge"));
        assertEq(keccak256(bytes(version)), keccak256("1"));
        assertEq(chainId, cid);
        assertEq(vc, BRIDGE);
        string memory entry = string.concat(
            '{"kind": "Domain", ',
            head(cid),
            ', "name": "WyecBridge", "version": "1", "digest": "',
            vm.toString(ds),
            '"}'
        );
        vm.revertToState(snap); // forget the throwaway deployment, keep the entry
        cases.push(entry);
    }

    function mintCase(uint256 cid, uint256 k, bytes32 lockId, uint256 amount, address to) internal {
        uint256 snap = vm.snapshotState();
        bytes32 sh = WyecEip712.mintStruct(lockId, amount, to);
        bytes32 d = WyecEip712.digest(WyecEip712.domainSeparator(cid, BRIDGE), sh);
        bytes memory sig = signLowS(pks[k], d);
        WyecBridge b = deployAt(cid, vm.addr(pks[k]));
        b.mint(lockId, amount, to, one(sig));
        assertEq(WrappedYcash(address(b.token())).balanceOf(to), amount);
        string memory fields = string.concat(
            '"lockId": "',
            vm.toString(lockId),
            '", "amount": "',
            vm.toString(amount),
            '", "to": "',
            vm.toString(to)
        );
        string memory t = tail(sh, d, k, sig);
        string memory entry = string.concat('{"kind": "Mint", ', head(cid), ", ", fields, '", ', t, "}");
        vm.revertToState(snap); // forget the throwaway deployment, keep the entry
        cases.push(entry);
    }

    function setGuardiansCase(uint256 cid, uint256 k, address[] memory g, uint8 threshold, uint256 adminNonce)
        internal
    {
        uint256 snap = vm.snapshotState();
        bytes32 sh = WyecEip712.setGuardiansStruct(g, threshold, adminNonce);
        bytes32 d = WyecEip712.digest(WyecEip712.domainSeparator(cid, BRIDGE), sh);
        bytes memory sig = signLowS(pks[k], d);
        WyecBridge b = deployAt(cid, vm.addr(pks[k]));
        setAdminNonce(b, adminNonce);
        b.setGuardians(g, threshold, one(sig));
        assertEq(b.threshold(), threshold);
        assertEq(b.adminNonce(), adminNonce + 1);
        string memory entry = string.concat(
            '{"kind": "SetGuardians", ',
            head(cid),
            ", ",
            guardiansFields(g, threshold, adminNonce),
            ", ",
            tail(sh, d, k, sig),
            "}"
        );
        vm.revertToState(snap); // forget the throwaway deployment, keep the entry
        cases.push(entry);
    }

    function setPausedCase(uint256 cid, uint256 k, bool paused, uint256 adminNonce) internal {
        uint256 snap = vm.snapshotState();
        bytes32 sh = WyecEip712.setPausedStruct(paused, adminNonce);
        bytes32 d = WyecEip712.digest(WyecEip712.domainSeparator(cid, BRIDGE), sh);
        bytes memory sig = signLowS(pks[k], d);
        WyecBridge b = deployAt(cid, vm.addr(pks[k]));
        setAdminNonce(b, adminNonce);
        // Pausable reverts on a no-op (ExpectedPause / EnforcedPause): start from the other state.
        if (!paused) stdstore.target(address(b)).sig("paused()").checked_write(true);
        b.setPaused(paused, one(sig));
        assertEq(b.paused(), paused);
        string memory t = tail(sh, d, k, sig);
        string memory entry = string.concat(
            '{"kind": "SetPaused", ',
            head(cid),
            ', "paused": ',
            paused ? "true" : "false",
            ', "adminNonce": "',
            vm.toString(adminNonce),
            '", ',
            t,
            "}"
        );
        vm.revertToState(snap); // forget the throwaway deployment, keep the entry
        cases.push(entry);
    }

    function setBridgeCase(uint256 cid, uint256 k, address newBridge, uint256 adminNonce) internal {
        uint256 snap = vm.snapshotState();
        bytes32 sh = WyecEip712.setBridgeStruct(newBridge, adminNonce);
        bytes32 d = WyecEip712.digest(WyecEip712.domainSeparator(cid, BRIDGE), sh);
        bytes memory sig = signLowS(pks[k], d);
        WyecBridge b = deployAt(cid, vm.addr(pks[k]));
        setAdminNonce(b, adminNonce);
        b.setBridge(newBridge, one(sig));
        assertEq(WrappedYcash(address(b.token())).bridge(), newBridge);
        string memory t = tail(sh, d, k, sig);
        string memory entry = string.concat(
            '{"kind": "SetBridge", ',
            head(cid),
            ', "newBridge": "',
            vm.toString(newBridge),
            '", "adminNonce": "',
            vm.toString(adminNonce),
            '", ',
            t,
            "}"
        );
        vm.revertToState(snap); // forget the throwaway deployment, keep the entry
        cases.push(entry);
    }

    function setMintLimitCase(uint256 cid, uint256 k, uint256 cap, uint256 window, uint256 adminNonce)
        internal
    {
        uint256 snap = vm.snapshotState();
        bytes32 sh = WyecEip712.setMintLimitStruct(cap, window, adminNonce);
        bytes32 d = WyecEip712.digest(WyecEip712.domainSeparator(cid, BRIDGE), sh);
        bytes memory sig = signLowS(pks[k], d);
        WyecBridge b = deployAt(cid, vm.addr(pks[k]));
        setAdminNonce(b, adminNonce);
        b.setMintLimit(cap, window, one(sig));
        assertEq(b.mintCap(), cap);
        assertEq(b.capWindow(), window);
        assertEq(b.adminNonce(), adminNonce + 1);
        string memory t = tail(sh, d, k, sig);
        string memory entry = string.concat(
            '{"kind": "SetMintLimit", ',
            head(cid),
            ', "mintCap": "',
            vm.toString(cap),
            '", "capWindow": "',
            vm.toString(window),
            '", "adminNonce": "',
            vm.toString(adminNonce),
            '", ',
            t,
            "}"
        );
        vm.revertToState(snap); // forget the throwaway deployment, keep the entry
        cases.push(entry);
    }

    /// The challenge is submitted against a real proposal with the case's id: the counter is set
    /// to id - 1, the signer proposes (amount 1 to 0x..01), then challenges with the case's
    /// signature.
    function challengeCase(uint256 cid, uint256 k, bytes32 lockId, uint256 proposalId) internal {
        uint256 snap = vm.snapshotState();
        bytes32 sh = WyecEip712.challengeStruct(lockId, proposalId);
        bytes32 d = WyecEip712.digest(WyecEip712.domainSeparator(cid, BRIDGE), sh);
        bytes memory sig = signLowS(pks[k], d);
        submitChallenge(cid, k, lockId, proposalId, sig);
        string memory t = tail(sh, d, k, sig);
        string memory entry = string.concat(
            '{"kind": "Challenge", ',
            head(cid),
            ', "lockId": "',
            vm.toString(lockId),
            '", "proposalId": "',
            vm.toString(proposalId),
            '", ',
            t,
            "}"
        );
        vm.revertToState(snap); // forget the throwaway deployment, keep the entry
        cases.push(entry);
    }

    // ------------------------------------------------------------------ helpers

    function submitChallenge(uint256 cid, uint256 k, bytes32 lockId, uint256 proposalId, bytes memory sig)
        internal
    {
        WyecBridge b = deployAt(cid, vm.addr(pks[k]));
        stdstore.target(address(b)).sig("proposalCount()").checked_write(proposalId - 1);
        bytes32 md = WyecEip712.digest(
            WyecEip712.domainSeparator(cid, BRIDGE), WyecEip712.mintStruct(lockId, 1, address(1))
        );
        assertEq(b.proposeMint(lockId, 1, address(1), signLowS(pks[k], md)), proposalId);
        b.challengeMint(lockId, proposalId, sig);
        assertEq(b.getProposal(lockId).id, 0);
        assertTrue(b.vetoed(lockId, vm.addr(pks[k])));
    }

    function guardiansFields(address[] memory g, uint8 threshold, uint256 adminNonce)
        internal
        pure
        returns (string memory list)
    {
        for (uint256 i = 0; i < g.length; i++) {
            list = string.concat(list, i == 0 ? '"' : ', "', vm.toString(g[i]), '"');
        }
        return string.concat(
            '"guardians": [',
            list,
            '], "threshold": ',
            vm.toString(uint256(threshold)),
            ', "adminNonce": "',
            vm.toString(adminNonce),
            '"'
        );
    }

    function head(uint256 cid) internal pure returns (string memory) {
        return
            string.concat(
                '"chainId": ', vm.toString(cid), ', "verifyingContract": "', vm.toString(BRIDGE), '"'
            );
    }

    function tail(bytes32 structHash, bytes32 d, uint256 k, bytes memory sig)
        internal
        returns (string memory)
    {
        Vm.Wallet memory w = vm.createWallet(pks[k]);
        bytes memory pub =
            abi.encodePacked(bytes1(w.publicKeyY % 2 == 0 ? 0x02 : 0x03), bytes32(w.publicKeyX));
        return string.concat(
            '"structHash": "',
            vm.toString(structHash),
            '", "digest": "',
            vm.toString(d),
            '", "privateKey": "',
            vm.toString(bytes32(pks[k])),
            '", "publicKey": "',
            vm.toString(pub),
            '", "signer": "',
            vm.toString(w.addr),
            '", "signature": "',
            vm.toString(sig),
            '"'
        );
    }

    function signLowS(uint256 pk, bytes32 d) internal pure returns (bytes memory) {
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(pk, d);
        require(uint256(s) <= 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0, "high-S");
        return abi.encodePacked(r, s, v);
    }

    function one(bytes memory sig) internal pure returns (bytes[] memory sigs) {
        sigs = new bytes[](1);
        sigs[0] = sig;
    }

    /// A fresh token + bridge with the bridge at BRIDGE on chain `cid`, `guardian` as 1-of-1, a
    /// 60-second challenge window, no rate limit.
    function deployAt(uint256 cid, address guardian) internal returns (WyecBridge) {
        vm.chainId(cid);
        WrappedYcash t = new WrappedYcash(BRIDGE);
        address[] memory g = new address[](1);
        g[0] = guardian;
        deployCodeTo(
            "WyecBridge.sol:WyecBridge",
            abi.encode(t, g, uint8(1), uint64(60), uint256(0), uint256(0)),
            BRIDGE
        );
        return WyecBridge(BRIDGE);
    }

    function setAdminNonce(WyecBridge b, uint256 n) internal {
        if (n != 0) stdstore.target(address(b)).sig("adminNonce()").checked_write(n);
        assertEq(b.adminNonce(), n);
    }
}
